name: diesel_monitor
description: A Flutter app for Smart Diesel Tank Monitoring System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Networking
  dio: ^5.4.0
  http: ^1.1.2

  # Local Storage
  shared_preferences: ^2.2.2

  # Charts
  fl_chart: ^0.66.0

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Internationalization
  intl: ^0.19.0

  # Utilities
  connectivity_plus: ^5.0.2
  udp: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/